# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size = 5>

**Submit as an HTML file** (see images below)

<font size = 3>

Step 1: Click the 3 dots in the toolbar for "More Actions"

<img src="practice_quiz_figures/step1.png" alt="drawing" width = "600"/>

***
Step 2: Choose "export"

<img src="practice_quiz_figures/step2.png" alt="drawing" width = "600"/>

***
Step 3: Select "HTML" from the dropdown window

<img src="practice_quiz_figures/step3.png" alt="drawing" width = "600"/>

***
Step 4: Select "Export" in the pop-up window.

<img src="practice_quiz_figures/step4.png" alt="drawing" width = "300"/>

Upload the .html file as your submission

<font size="5"> 

Print your name below

In [ ]:
# Write your answer here

print("Kevin Gan")

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should work as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [ ]:
# Write your answer here:
print("I will abide by Emory's code of conduct")

<font size = "5">

Import pandas

In [4]:
import pandas as pd
import numpy as np


<font size = "5">

(1) Replace the values of a column

<font size = "3">

- Consider the DataFrame ``df_movies`` created below.
- In the "country" column, change the values "American" and "Korean" to "USA" and "ROK" respectively
- Do this by using the ``.replace`` method.

In [3]:
# Create example DataFrame - **don't change this**
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
country = ["American", "American", "France", "Korean", "Thailand", "Korean", "France",
    "France", "Japan", "Italy", "American"]
runtime = [106, 119, 108, 120, 97, 115, 96, 91, 88, 98, 120]
year = [2023, 1941, 2017, 2017, 2004, 2003, 1967, 1964, 1977, 1977, 1986]
movie_dict = {"title" : titles, "country" : country, "runtime" : runtime, "year" : year}
df_movies = pd.DataFrame(movie_dict)


# your answer here
to_replace = ["American", "Korean"]
replace_with = ["USA", "ROK"]

df_movies["country"] = df_movies["country"].replace(to_replace, replace_with)

display(df_movies)

                         title   country  runtime  year
0                   Past Lives       USA      106  2023
1                 Citizen Kane       USA      119  1941
2                      Revenge    France      108  2017
3                         Okja       ROK      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters       ROK      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet       USA      120  1986

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["1941-1967","1968-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [6]:
# your code here
group_bins = [1940, 1967, 1999, np.inf]

group_labels = ["1941-1967", "1968-1999", "2000-onwards"]
df_movies["year_brackets"] = pd.cut(df_movies["year"], bins = group_bins, right = True, labels = group_labels)

display(df_movies)

                         title   country  runtime  year year_brackets
0                   Past Lives       USA      106  2023  2000-onwards
1                 Citizen Kane       USA      119  1941     1941-1967
2                      Revenge    France      108  2017  2000-onwards
3                         Okja       ROK      120  2017  2000-onwards
4                      Shutter  Thailand       97  2004  2000-onwards
5        A Tale of Two Sisters       ROK      115  2003  2000-onwards
6                  La Chinoise    France       96  1967     1941-1967
7   The Umbrellas of Cherbourg    France       91  1964     1941-1967
8                        House     Japan       88  1977     1968-1999
9                     Suspiria     Italy       98  1977     1968-1999
10                 Blue Velvet       USA      120  1986     1968-1999

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [23]:
# Write your answer here:

df_movies.rename(columns = {"runtime" : "runtime(minutes)"},  inplace= True)

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, merging on <br>
the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [27]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
scores = [7.8, 8.2, 6.4, 7.3, 7.0, 7.1, 6.9, 7.8, 7.2, 7.3, 7.7]
directors = ["Celine Song", "Orson Welles", "Coralie Fargeat", "Bong Joon Ho", 
    "Banjong Pisanthanakun", "Kim Jee-woon", "Jean-Luc Godard", "Jacques Demy", 
    "Nobuhiko Obayashi", "Dario Argento", "David Lynch"]

movie_dict2 = {"title" : titles, "imdb_score" : scores, "director" : directors}
df_scores = pd.DataFrame(movie_dict2)



# Write your answer here:
df_scores_subset = df_scores.iloc[:, [0,1]]
df_with_scores = pd.merge(left = df_movies, right = df_scores_subset, on = "title", how = "left")

<font size = "5">

(5) Aggregate and sort

<font size = "3">

- Using the merged dataset you created above, do the following in a single line by chaining:
    - Group the dataset by "country"
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score
    - Score by average IMBD score in **descending order**

Print the resulting DataFrame

In [ ]:
# Write your answer here:
# country_group = df_with_scores.groupby("country")
# df_agg = country_group.agg(average_runtime = ("runtime(minutes)", "mean"), 
#                   max_runtime = ("runtime(minutes)", max), 
#                   average_score = ("imdb_score", "mean"), 
#                   min_score = ("imdb_score", min))

# df_final = df_agg.sort_values(by = "average_score", ascending = False)

print(df_final)

df_final = (df_with_scores.groupby("country").agg(average_runtime = ("runtime(minutes)", "mean"), 
                                                 max_runtime = ("runtime(minutes)", max), 
                                                 average_score = ("imdb_score", "mean"), 
                                                 min_score = ("imdb_score", min))).sort_values(by = "average_score", ascending=False)
print(df_final)

          average_runtime  max_runtime  average_score  min_score
country
USA            115.000000          120       7.900000        7.7
Italy           98.000000           98       7.300000        7.3
Japan           88.000000           88       7.200000        7.2
ROK            117.500000          120       7.200000        7.1
France          98.333333          108       7.033333        6.4
Thailand        97.000000           97       7.000000        7.0
          average_runtime  max_runtime  average_score  min_score
country
USA            115.000000          120       7.900000        7.7
Italy           98.000000           98       7.300000        7.3
Japan           88.000000           88       7.200000        7.2
ROK            117.500000          120       7.200000        7.1
France          98.333333          108       7.033333        6.4
Thailand        97.000000           97       7.000000        7.0

/var/folders/29/2z6k0lkd3sbgy29ttd1nby1w0000gn/T/ipykernel_70230/1399967593.py:3: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_agg = country_group.agg(average_runtime = ("runtime(minutes)", "mean"),
/var/folders/29/2z6k0lkd3sbgy29ttd1nby1w0000gn/T/ipykernel_70230/1399967593.py:3: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df_agg = country_group.agg(average_runtime = ("runtime(minutes)", "mean"),
/var/folders/29/2z6k0lkd3sbgy29ttd1nby1w0000gn/T/ipykernel_70230/1399967593.py:12: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_final = (df_with_scores.groupby("country").agg(average_runtime = ("runtime(minutes)", "mean"),
/var/folders/29/2z6k0lkd3sbgy29ttd1nby1w0000gn/T/ipykernel_70230/1399967593.py:12: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df_final = (df_with_scores.groupby("country").agg(average_runtime = ("runtime(minutes)", "mean"),

<font size = "5">

(6) Query and Aggregate

<font size = "3">

Using the merged dataset you created above, do the following in a single line by chaining:

- Subset the observations for 'country == France' using ```.query()```
- Sort the values by year (oldest first)
- Extract the two oldest movies

Print the resulting DataFrame to the screen

In [46]:
# Write your answer here:
# df_france = df_with_scores.query("country == 'France'")
# df_france_sorted = df_france.sort_values(by = "year", ascending=True)
# df_oldest_two = df_france_sorted.iloc[0:2, :]
# print(df_oldest_two)

(df_with_scores.query("country == 'France'")).sort_values(by = "year", ascending = True).iloc[:2, :]

,title,country,runtime(minutes),year,year_brackets,imdb_score
7,The Umbrellas of Cherbourg,France,91,1964,1941-1967,7.8
6,La Chinoise,France,96,1967,1941-1967,6.9